### ISSUE TITLE
Upgrading Dual Extruder Parts

### ISSUE THREAD

**Issue by Paulebomber** [open3dengineering/i3_Berlin#17]
Hey, da mein Drucker mittlerweile tadellos läuft und druckt, wollte ich mal fragen welche Teile ihr für den Extruder verwendet also z.B. welchen Stepper-Motor könnt ihr empfehlen?
Hot-End müsste ja das E3D sein...
Ich glaube, dass ich V5 habe, sollte ich das andere auch als V5 oder V6 nehmen?
Welchen Thermistor benötige ich?
Letzte und vielleicht entscheidene Frage: Woher bekomme ich die Teile am besten?
Wäre super nett, wenn ihr mich bei der Idee dual-Extruder unterstützen könntet
LG und Vielen Dank,
Paul

**Comment by ugu** [comment]
Hello Paul,

You can get all the parts directly from us, if you already own a V5, we advise you to continue with it as we don't have the parts adjusted for 2 different versions (the V6 is 1 cm shorter in length...) we do have an upgrade that avoid most of the jamming problems the original E3D V5 had, we also added a self adjusting idler(with a spring) to be able to cope with filaments that are not so constant in diameter so we would suggest that you send us your original aluminium parts and we will make that upgrade without any additional cost...

Greetings
Hugo

(sorry for replying in English, but my written german sucks! :D )

**Comment by Paulebomber** [comment]
Hey Hugo,
Thanks for your fast answer. How much would your kit cost?
Bran already told me about the spring idler and told me as well, that he is going to do it for me but the CNC machine has been broken. It would be no problem for me to meetup at some point, because I think it's a bit pointless to send the aluminum parts, while I live in Berlin
;) 
Greetings
Paul

**Comment by mangtronix** [comment]
Hi Hugo,

I have a dual extruder i3 Berlin and I'm also interested in the spring idler upgrade so I can print with experimental and self-extruded filaments.  I'm also in Berlin and I'll be at Fab Lab a few times this month.

I wonder if a v6 hotend with the new extended "Volcano" heater block would match the length of the v5 hotend. Unfortunately I haven't found any mechanical drawings and it looks like it's out of stock. Still cool though! http://e3d-online.com/blog/volcano_release

I'm currently using the v5 hotend with the v6 nozzle and I find the newer nozzle gives a slight improvement for jamming and retracts.  I got the v6 nozzle directly from E3D.

Best,
  - mang

**Comment by ugu** [comment]
@Paulebomber  Sorry for replying late but sickness kicked in.... The upgrade Kit containing all the parts will cost you 150€.
As for the milling, the Cnc is fixed now, we are working on a date to do it and we are notifying all printer owners to send back their plates. We want to do it all at the same time to reduce the amount of work needed for the procedure. we will notify you with that as soon as the date is defined.

@mangtronix  looking at the pics of the Vulcano we also think it might work, but because we didn't got one yet we are not sure it will, but if you are willing to try that setup, we are here to help you with any problems that might come along.
We made our own custom nozzles for the V5 that work like charm in surface quality, but the problems with the Jamming and retracting are not coming from the nozzle, but the Heatbreak and Heatsink.
If you are coming to The Fablab this month we can discuss this subject a little more in detail...

Greetings to both....

Hugo

**Comment by vela3** [comment]
Hi Paul, 

This monday I would like to start milling the extruder upgrades. 
Please mail me on info@laydrop(dot)com for more info.
